import { useState, useEffect, useRef } from 'react'
import DiagnosticHeader from '../components/diagnostic/DiagnosticHeader'
import HealthScoreGauge from '../components/diagnostic/HealthScoreGauge'
import CategoryGrid from '../components/diagnostic/CategoryGrid'
import ConversionFunnel from '../components/diagnostic/ConversionFunnel'
import FindingsPanel from '../components/diagnostic/FindingsPanel'
import ActionPlanTable from '../components/diagnostic/ActionPlanTable'
import ImpactEffortMatrix from '../components/diagnostic/ImpactEffortMatrix'
import RevenueImpactChart from '../components/diagnostic/RevenueImpactChart'
import CompetitorSnapshot from '../components/diagnostic/CompetitorSnapshot'
import OperatorAlignment from '../components/diagnostic/OperatorAlignment'
import StowStackCTA from '../components/diagnostic/StowStackCTA'
import DecayProjector from '../components/diagnostic/DecayProjector'
import { generateReport } from '../lib/reportGenerator'
import { Rocket } from 'lucide-react'

export default function SharedAudit({ slug }) {
  const [audit, setAudit] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [darkMode, setDarkMode] = useState(true)
  const [expandedCategory, setExpandedCategory] = useState('occupancy_momentum')
  const [meta, setMeta] = useState({})
  const findingsRef = useRef(null)

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch(`/api/audit-load?slug=${encodeURIComponent(slug)}`)
        if (!res.ok) {
          const data = await res.json().catch(() => ({}))
          throw new Error(data.error || 'Audit not found')
        }
        const data = await res.json()
        setAudit(data.audit)
        setMeta({ createdAt: data.createdAt, views: data.views, facilityName: data.facilityName })
      } catch (err) {
        setError(err.message)
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [slug])

  function handleExpandCategory(key) {
    setExpandedCategory(key)
    findingsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }

  async function handleDownloadReport() {
    if (!audit) return
    try {
      await generateReport(audit)
    } catch (err) {
      console.error('Report generation failed:', err)
    }
  }

  // Loading
  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center"
        style={{ background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)' }}>
        <div className="text-center">
          <div className="w-12 h-12 mx-auto mb-4 border-3 border-green-500/30 border-t-green-500 rounded-full animate-spin" />
          <p className="text-slate-400 text-sm">Loading audit...</p>
        </div>
      </div>
    )
  }

  // Error / not found
  if (error || !audit) {
    return (
      <div className="min-h-screen flex items-center justify-center"
        style={{ background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)' }}>
        <div className="max-w-md text-center px-4">
          <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-slate-800 flex items-center justify-center">
            <span className="text-2xl">🔍</span>
          </div>
          <h2 className="text-xl font-bold text-white mb-2">Audit Not Found</h2>
          <p className="text-slate-400 text-sm mb-6">
            {error || 'This audit link may have expired or is invalid.'}
          </p>
          <a
            href="/"
            className="inline-flex px-6 py-2.5 rounded-lg bg-green-500 text-white font-medium hover:bg-green-600 transition-colors"
          >
            Visit StowStack
          </a>
        </div>
      </div>
    )
  }

  const dm = darkMode

  return (
    <div data-theme={dm ? 'dark' : 'light'} className={dm ? 'bg-slate-900 text-white' : 'bg-slate-50 text-slate-900'}>
      {/* CTA Banner for shared view */}
      <div className="bg-gradient-to-r from-green-600 to-emerald-600 px-4 py-2.5 text-center">
        <div className="flex items-center justify-center gap-2 flex-wrap">
          <Rocket className="w-4 h-4 text-white/80" />
          <span className="text-sm text-white/90">
            This audit was generated by <strong className="text-white">StowStack</strong> — the self-storage demand engine
          </span>
          <a
            href="https://stowstack.co"
            className="inline-flex px-3 py-1 rounded-full text-xs font-medium bg-white/20 text-white hover:bg-white/30 transition-colors"
          >
            Get Your Free Audit →
          </a>
        </div>
      </div>

      <DiagnosticHeader
        facility={audit.facility_summary}
        darkMode={dm}
        onToggleDarkMode={() => setDarkMode(!dm)}
        onDownloadReport={handleDownloadReport}
        readOnly
      />

      <main className="max-w-[1400px] mx-auto px-4 sm:px-6 py-8 space-y-8">
        {/* Facility info bar */}
        {audit.facility_summary && (
          <div className={`flex flex-wrap items-center gap-x-6 gap-y-2 text-xs ${
            dm ? 'text-slate-500' : 'text-slate-400'
          }`}>
            {audit.facility_summary.address && <span>{audit.facility_summary.address}</span>}
            {audit.facility_summary.stage && <span>{audit.facility_summary.stage}</span>}
            {audit.facility_summary.unit_count_range && <span>{audit.facility_summary.unit_count_range} units</span>}
            {audit.facility_summary.occupancy_range && <span>{audit.facility_summary.occupancy_range} occupancy</span>}
            {meta.createdAt && (
              <span>Generated {new Date(meta.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span>
            )}
            {meta.views > 0 && <span>{meta.views} view{meta.views !== 1 ? 's' : ''}</span>}
          </div>
        )}

        <HealthScoreGauge
          score={audit.overall_score?.score || 0}
          summary={audit.overall_score?.summary}
          topIssues={audit.overall_score?.top_3_issues}
          topStrengths={audit.overall_score?.top_3_strengths}
          darkMode={dm}
        />

        <CategoryGrid
          categories={audit.categories}
          darkMode={dm}
          onExpandCategory={handleExpandCategory}
        />

        <ConversionFunnel funnel={audit.conversion_funnel} darkMode={dm} />

        <div ref={findingsRef}>
          <FindingsPanel
            categories={audit.categories}
            expandedCategory={expandedCategory}
            onChangeCategory={setExpandedCategory}
            darkMode={dm}
          />
        </div>

        <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
          <ActionPlanTable actions={audit.priority_action_plan} darkMode={dm} />
          <ImpactEffortMatrix actions={audit.priority_action_plan} darkMode={dm} />
        </div>

        <RevenueImpactChart revenue={audit.revenue_impact} darkMode={dm} />

        <DecayProjector audit={audit} darkMode={dm} />

        <OperatorAlignment alignment={audit.operator_alignment} darkMode={dm} />

        <CompetitorSnapshot competitor={audit.competitor_analysis} darkMode={dm} />

        <StowStackCTA opportunities={audit.stowstack_opportunities} darkMode={dm} />

        {/* Footer with CTA */}
        <div className={`text-center py-8 space-y-3 ${dm ? 'text-slate-600' : 'text-slate-400'}`}>
          <div className="text-xs">
            Generated by StowStack Facility Diagnostic
            {meta.createdAt && ` · ${new Date(meta.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`}
          </div>
          <a
            href="https://stowstack.co"
            className="inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-green-500 text-white text-sm font-medium hover:bg-green-600 transition-colors"
          >
            <Rocket className="w-4 h-4" />
            Get Your Free Facility Audit
          </a>
        </div>
      </main>
    </div>
  )
}
